---
title: ''
date: ""
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(knitr)
library('ggspectra')
library("ggpmisc")
library("lubridate")
library(dplyr)
library(ggplot2)
library(tibble)
library(PlayerRatings)
library(tidyr)
library(reactable)
library(htmltools)
```
<br>
<br>
<br>
<br>
<br>

### Personal Elo ranking: 18-04-2023
```{r echo=FALSE}
inp_data <- readRDS("data/123.RData")
# filter by DATE !!!
inp_data = inp_data %>% filter(game_date > "2023-07-25" &  competition == "Liga Profesional Argentina" & min > 0)
htmltools::tags$link(
  href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback",
  rel = "stylesheet"
)
# create special dataframe
ctd = inp_data[,c("team", "player", "game_date" , "min","PlayerRateAfter","result")]
ctd$diff = inp_data$PlayerRateAfter - inp_data$PlayerRateBefore
ctd = ctd %>% relocate(diff, .after = result) 
ctd$photo = ""
ctd$PlayerRateAfter = round(ctd$PlayerRateAfter,1)
ctd$diff = round(ctd$diff,1)
ctd = ctd %>% arrange(desc(PlayerRateAfter)) %>% mutate(rank = row_number()) %>% relocate(rank, .before = team) 
ctd = ctd %>% relocate(photo, .after = team)
ctd = ctd %>% relocate(PlayerRateAfter, .after = diff)
ctd = ctd %>% arrange(desc(PlayerRateAfter))


# top_n
# ctd[1:10,]$photo = c("bjadvincula","bjvilla","bjfigal","bjvarela","bjoromero", "ccrius", "dyjasoto" "hgsoto", "rparmani", "rpcasco", "rhauche",  "rmoreno", "rsigali", "rinsua","slhernandez", "slcerutti",  "slgattoni" "slbatalla" "slelias",                     "tluciatti", "tcastro" ,   "talfranco", "talsosa")
#TOP 15
ctd[1:15,]$photo = c("rpcasco", "rpbarco","rparmani","bjfigal", "talsosa", 
                     "ccrius","slbatalla","pmacagno","slelias","rhauche",
                    "rsigali","rmura", "slgiay", "vggomez",   "tluciatti")


#                                       +1 because of hours difference
ctd$game_date = as.Date(ctd$game_date) +1
ctd$game_date = format(as.Date(ctd$game_date), "%d-%m")
qr = c( min(ctd$diff) + (((max(ctd$diff) - min(ctd$diff)) / 3)),min(ctd$diff) + (((max(ctd$diff) - min(ctd$diff)) / 3))*2)

# add valor de mercado
ctd$value = ""
ctd[1:15,]$value = c("€1.0m","€8.5m","€2.2m","€4m","€4.8",
                     "€0.2m","€2m","€0.85m","€2.5m","€0.35m",
                     "€1.2m","€3.5m","€4m","€1.5m","€0.45m")

top_n = ctd[1:15,]

# add doge rank
#top_n$doge = case_when(top_n$diff < qr[1] ~ "wd",
#                       top_n$diff >= qr[1] & top_n$diff < qr[2]~ "ud",
#                       top_n$diff >= qr[2] ~ "sd")

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}
rating_column <- function(maxWidth = 55, ...) {
  colDef(maxWidth = maxWidth, align = "center", class = "cell number", ...)
}
off_rating_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 1.3)
```

```{r table, echo=FALSE}
## Drawing table

BuYlRd <- function(x) rgb(colorRamp(c("#7fb7d7", "#ffffbf", "#fc8d59"))(x), maxColorValue = 255)

reactable(
  top_n,
  columns = list(
    rank = colDef(name = "#"),
    team = colDef(name = "Equipo",
      cell = function(value) {
        img_src <- knitr::image_uri(sprintf("logo/%s.png", value))
        image <- img(src = img_src, style = "height: 48px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 48px", image)
          )
      },
      align = "center",
      maxWidth = 64
    ),
    photo = colDef(name = "",
                   cell = function(value) { img_src <- knitr::image_uri(sprintf("players/top15/%s.png", value))
                   image <- img(src = img_src, style = "height: 57px", alt = value)
                   tagList(
                     div(style = "display: inline-block; width: 57px", image))
                   },
                   maxWidth = 64
                   ),
    player = colDef(name = "Jugador",
                      maxWidth = 100,
                   style = list(color = color, fontWeight = "bold")),
    game_date = colDef(name = "Último partido",
                       maxWidth = 65),
    min = colDef(name = "Min.",
                 format = colFormat(digits = 0),
                 maxWidth = 50),
    result = colDef(name = "Resultado",
      cell = function(value) {
        img_src <- knitr::image_uri(sprintf("result/%s.png", value))
        image <- img(src = img_src, style = "height: 20px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 20px", image)
          )
      },
      align = "center",
      maxWidth = 50
    ),
    PlayerRateAfter = colDef(name = "Elo total",
                             maxWidth = 64,
                             format = colFormat(digits = 1),
                             align = "left",
                            style = list(fontWeight = "bold")
                            ),
                             
    diff = rating_column(
      name = "Elo +/-",
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
        scaled <- (value - min(ctd$diff)) / (max(ctd$diff) - min(ctd$diff))
        color <- off_rating_color(scaled)
        value <- format(round(value, 1), nsmall = 1)
        div(class = "spi-rating", style = list(background = color, fontWeight = "bold"), value)
      }
    ),
    doge = colDef(name = "Doge rank",
      cell = function(value) {
        img_src <- knitr::image_uri(sprintf("doge/%s.png", value))
        image <- img(src = img_src, style = "height: 48px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 48px", image)
          )
      },
      align = "center",
      maxWidth = 64
    ),
    value = colDef(name = "Valor de mercado",
                       maxWidth = 74, 
                   align = "center",
                  style = list(fontWeight = "bold"))
    ),
  defaultColDef = colDef(headerStyle = list(fontWeight=200), vAlign = "center"),
  defaultSorted = "PlayerRateAfter",
  defaultSortOrder = "desc",
  borderless = TRUE,
  height = 900,
  defaultPageSize = 5,
  style = list(fontFamily = "Karla, Helvetica Neue"),
)
```


```{css styles, eval=FALSE, echo = FALSE}
.spi-rating {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: auto;
  width: 1.875rem;
  height: 1.875rem;
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  color: #000;
  font-size: 0.8125rem;
  letter-spacing: -1px;
}
.title {
  margin: 0.75rem 0.375rem 1.5rem;
  padding: 0;
  font-size: 0.5rem;
  font-weight: 600;
}

.header {
  border-bottom-color: #555;
  font-size: 0.8125rem;
  font-weight: 400;
  text-transform: uppercase;
}
```
