---
title: ''
date: ""
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(knitr)
library('ggspectra')
library("ggpmisc")
library("lubridate")
library(dplyr)
library(ggplot2)
library(tibble)
library(PlayerRatings)
library(tidyr)
library(reactable)
library(htmltools)
```
<br>
<br>
<br>
<br>
<br>

###
```{r echo=FALSE}
inp_data <- readRDS("data/lastSW14062023.RData")
# filter by DATE !!!
inp_data = inp_data %>% filter(game_date > "2023-06-05"  & min > 0)
htmltools::tags$link(
  href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback",
  rel = "stylesheet"
)
# create special dataframe
ctd = inp_data[,c("team", "player","PlayerRateAfter")]
ctd$photo = ""
ctd$PlayerRateAfter = round(ctd$PlayerRateAfter,1)
ctd$Position = "Def"
ctd = ctd %>% arrange(desc(PlayerRateAfter)) %>% mutate(rank = row_number()) %>% relocate(rank, .before = team) 
ctd = ctd %>% relocate(photo, .after = team) %>% relocate(Position, .after = player)
ctd = ctd %>% arrange(desc(PlayerRateAfter))


# top_n
# ctd[1:10,]$photo = c("bjadvincula","bjvilla","bjfigal","bjvarela","bjoromero", "ccrius", "dyjasoto", "dyjunsain", "dyjlopez", "ejrodriguez", "eandujar","ezuqui", "hgsoto", "nobsforza","pmacagno","rparmani", "rpcasco", "rppdiaz", "rpperez""rhauche",  "rmoreno", "rsigali", "rinsua","slhernandez", "slcerutti",  "slgattoni" "slbatalla" "slelias", "talvillagra", "tluciatti", "tcastro" ,   "talfranco", "talsosa")
#TOP 15
ctd[1:15,]$photo = c("dyjasoto", "rpcasco","rparmani","ccrius", "talsosa", 
                      "slhernandez","rpbarco", "rmoreno","slcerutti","dyjunsain",
                      "bjfigal", "rppdiaz", "dyjlopez", "talvillagra", "nobsforza")
ctd[1:15,]$Position = c("Med", "Med", "Med", "Med", "Med",
                        "Arq", "Med", "Def", "Def", "Med",
                        "Def", "Def", "Med", "Def", "Med")

#                                       +1 because of hours difference
# add valor de mercado
ctd$value = ""
ctd[1:15,]$value = c("€1.5m","€1.2m","€3m","€0.2m","€4m",
                     "€3.2m","€6m","€8m","€0.8m","€4m",
                     "€4m","€4.5m","€0.5m","€6.5m","€3.5m")

top_n = ctd[1:15,]

# add doge rank
#top_n$doge = case_when(top_n$diff < qr[1] ~ "wd",
#                       top_n$diff >= qr[1] & top_n$diff < qr[2]~ "ud",
#                       top_n$diff >= qr[2] ~ "sd")

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}
rating_column <- function(maxWidth = 55, ...) {
  colDef(maxWidth = maxWidth, align = "center", class = "cell number", ...)
}
off_rating_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 1.3)
```

```{r table, echo=FALSE}
## Drawing table

BuYlRd <- function(x) rgb(colorRamp(c("#7fb7d7", "#ffffbf", "#fc8d59"))(x), maxColorValue = 255)

reactable(
  top_n,
  columns = list(
    rank = colDef(name = "#",
                  maxWidth = 65),
    team = colDef(name = "Equipo",
      cell = function(value) {
        img_src <- knitr::image_uri(sprintf("logo/%s.png", value))
        image <- img(src = img_src, style = "height: 48px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 48px", image)
          )
      },
      align = "center",
      maxWidth = 64
    ),
    photo = colDef(name = "",
                   cell = function(value) { img_src <- knitr::image_uri(sprintf("players/top15/%s.png", value))
                   image <- img(src = img_src, style = "height: 57px", alt = value)
                   tagList(
                     div(style = "display: inline-block; width: 57px", image))
                   },
                   maxWidth = 64
                   ),
    player = colDef(name = "Jugador",
                      maxWidth = 100,
                   style = list(color = color, fontWeight = "bold")),
        PlayerRateAfter = colDef(name = "Elo total",
                             maxWidth = 64,
                             format = colFormat(digits = 1),
                             align = "left",
                            style = list(fontWeight = "bold")
                            ),
      Position = colDef(name = "Posición",
                       maxWidth = 75,
                      align = "center"),
        PlayerRateAfter = colDef(name = "Elo total",
                             maxWidth = 64,
                             format = colFormat(digits = 1),
                             align = "left",
                            style = list(fontWeight = "bold")
                            ),
  value = colDef(name = "Valor de mercado",
                       maxWidth = 74, 
                   align = "center",
                  style = list(fontWeight = "bold"))
    ),
  defaultColDef = colDef(headerStyle = list(fontWeight=200), vAlign = "center"),
  defaultSorted = "PlayerRateAfter",
  defaultSortOrder = "desc",
  borderless = TRUE,
  height = 900,
  defaultPageSize = 5,
  style = list(fontFamily = "Karla, Helvetica Neue"),
)
```


```{css styles, eval=FALSE, echo = FALSE}
.spi-rating {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: auto;
  width: 1.875rem;
  height: 1.875rem;
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  color: #000;
  font-size: 0.8125rem;
  letter-spacing: -1px;
}
.title {
  margin: 0.75rem 0.375rem 1.5rem;
  padding: 0;
  font-size: 0.5rem;
  font-weight: 600;
}

.header {
  border-bottom-color: #555;
  font-size: 0.8125rem;
  font-weight: 400;
  text-transform: uppercase;
}
```
