---
title: 'Actualización de calificación Elo: CA Patronato'
date: "20-01-2024"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(knitr)
library('ggspectra')
library("ggpmisc")
library("lubridate")
library(dplyr)
library(ggplot2)
library(tibble)
library(PlayerRatings)
library(tidyr)
library(reactable)
library(htmltools)
```

### P
```{r echo=FALSE}
t_data <- readRDS("data/lastSW01052023.RData")
# create special dataframe
t_data = t_data %>% filter(game_date > "2023-04-26" & competition == "Liga Profesional Argentina" & min > 0)
#t_data = t_data %>% filter(game_date > "2023-02-23" & min > 0)
t_data$diff = t_data$TeamRateAfter - t_data$TeamRateBefore
t_data2 = unique(t_data[c("team", "TeamRateAfter","diff", "result")])
# Add team logo
t_data2$logo = paste0(t_data2$team, ".png")
t_data2 = t_data2 %>% arrange(desc(TeamRateAfter)) %>% mutate(rank = row_number()) %>% relocate(rank, .before = team) %>% relocate(logo, .after = rank) 

# filter by DATE !!!
htmltools::tags$link(
  href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback",
  rel = "stylesheet"
)

qr = c( min(t_data2$diff) + (((max(t_data2$diff) - min(t_data2$diff)) / 3)),min(t_data2$diff) + (((max(t_data2$diff) - min(t_data2$diff)) / 3))*2)

t_data2$doge = case_when(t_data2$diff < qr[1] ~ "wd",
                       t_data2$diff >= qr[1] & t_data2$diff < qr[2]~ "ud",
                       t_data2$diff >= qr[2] ~ "sd")
make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}
rating_column <- function(maxWidth = 55, ...) {
  colDef(maxWidth = maxWidth, align = "center", class = "cell number", ...)
}
off_rating_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 1.3)
```

```{r table, echo=FALSE}
## Drawing table

BuYlRd <- function(x) rgb(colorRamp(c("#7fb7d7", "#ffffbf", "#fc8d59"))(x), maxColorValue = 255)

reactable(
  t_data2,
  columns = list(
    rank = colDef(name = "#"),
    logo = colDef(name = "",
      cell = function(value) {
        img_src <- knitr::image_uri(sprintf("logo/%s", value))
        image <- img(src = img_src, style = "height: 48px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 48px", image)
          )
      },
      align = "center",
      maxWidth = 64
    ),
    team = colDef(name = "Equipo",
                      maxWidth = 110,
                   style = list(color = color, fontWeight = "bold")),
    result = colDef(name = "Último partido",
      cell = function(value) {
        img_src <- knitr::image_uri(sprintf("result/%s.png", value))
        image <- img(src = img_src, style = "height: 20px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 20px", image)
          )
      },
      align = "center",
      maxWidth = 64
    ),
    TeamRateAfter = colDef(name = "Plantel Elo",
                             maxWidth = 90,
                             format = colFormat(digits = 1),
                             align = "right",
                            ),
                             
    diff = rating_column(
      name = "+ / -",
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
        scaled <- (value - min(t_data2$diff)) / (max(t_data2$diff) - min(t_data2$diff))
        color <- off_rating_color(scaled)
        value <- format(round(value, 1), nsmall = 1)
        div(class = "spi-rating", style = list(background = color, fontWeight = "bold"), value)
      }
    ),
    doge = colDef(name = "Doge rank",
      cell = function(value) {
        img_src <- knitr::image_uri(sprintf("doge/%s.png", value))
        image <- img(src = img_src, style = "height: 48px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 48px", image)
          )
      },
      align = "center",
      maxWidth = 64
    )
    ),
  defaultColDef = colDef(headerStyle = list(fontWeight=200), vAlign = "center"),
  defaultSorted = "TeamRateAfter",
  defaultSortOrder = "desc",
  borderless = TRUE,
  height = 600,
  defaultPageSize = 7,
  #
  style = list(fontFamily = "Karla, Helvetica Neue"
              ),
  
)
```


```{css styles, eval=FALSE, echo = FALSE}
.spi-rating {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: auto;
  width: 1.875rem;
  height: 1.875rem;
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  color: #000;
  font-size: 0.8125rem;
  letter-spacing: -1px;
}
.title {
  margin: 0.75rem 0.375rem 1.5rem;
  padding: 0;
  font-size: 0.5rem;
  font-weight: 600;
}

.header {
  border-bottom-color: #555;
  font-size: 0.8125rem;
  font-weight: 400;
  text-transform: uppercase;
}
```
