---
title: "Untitled"
author: "Nacho Krukovsky"
date: "2023-06-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library('ggspectra')
library("ggpmisc")
library("lubridate")
library(dplyr)
library(ggplot2)
library(tibble)
library(PlayerRatings)
library(tidyr)
library(reactable)
library(htmltools)
```

## LIGA PROFESIONAL DE FÚTBOL - FECHA 27

```{r echo=FALSE}
###                     SCOREBOARD
####                LIGA PROFESIONAL DE FÚTBOL
inp_data <- readRDS("data/123.RData")

inp_data = inp_data %>% filter(game_date > "2023-07-25" & competition == "Liga Profesional Argentina" & min > 0 & is_home == 1) %>% arrange(game_date)
#inp_data = inp_data %>% filter(game_date > "2023-08-24" & min > 0 & is_home == 1) %>% arrange(game_date)

# Фильтруем дубли
inp_data = inp_data[inp_data$game_date != "2023-07-24" | inp_data$team != "Gimnasia La Plata", ]   

# Count diff
inp_data$diff = inp_data$TeamRateAfter - inp_data$TeamRateBefore

out_data = data.frame(logo_home = paste0(inp_data$team, ".png"),
                      elo_home = round(inp_data$TeamRateAfter,1),
                      dif_home = round(inp_data$diff,1),
                      team_home = toupper(inp_data$team),
                      points_home = inp_data$score_h,
                      tire = "-",
                      points_away = inp_data$score_a,
                      team_away = toupper(inp_data$rival),
                      elo_away = round(inp_data$RivalRateBefore - inp_data$diff,1),
                      dif_away = round(-inp_data$diff,1),
                      logo_away = paste0(inp_data$rival, ".png"))
out_data = unique(out_data)

# Дублируем все записи
# Empty data frame to store duplicated rows
out_data_new <- data.frame()

# Duplicate each row line by line
for (i in 1:nrow(out_data)) {
  row <- out_data[i, ]
  out_data_new <- rbind(out_data_new, row, row)
}
# Создаем новый датафрейм с пустыми строками
out_data_new <- out_data_new %>%
  mutate(
    logo_home = ifelse(row_number() %% 2 == 0, NA, logo_home),
    elo_home = ifelse(row_number() %% 2 == 0, NA, elo_home),
    dif_home = ifelse(row_number() %% 2 == 0, NA, dif_home),
    team_home = ifelse(row_number() %% 2 == 0, NA, team_home),
    points_home = ifelse(row_number() %% 2 == 0, NA, points_home),
    tire = ifelse(row_number() %% 2 == 0, NA, tire),
    points_away = ifelse(row_number() %% 2 == 0, NA, points_away),
    team_away = ifelse(row_number() %% 2 == 0, NA, team_away),
    elo_away = ifelse(row_number() %% 2 == 0, NA, elo_away),
    dif_away = ifelse(row_number() %% 2 == 0, NA, dif_away),
    logo_away = ifelse(row_number() %% 2 == 0, NA, logo_away)
  )

# Reset row names
rownames(out_data_new) <- NULL

# Style preparations
make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}
off_rating_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 1.3)
reactable(
  out_data_new,
  striped = T,
  theme = reactableTheme(borderColor = "#dfe2e5",
    stripedColor = "#f6f8fa",
    highlightColor = "#f0f5f9",
    color = "#555555",
    cellPadding = "0.5px 5px",
    
    style = list(
      fontFamily = "Champions"
    ),
    searchInputStyle = list(width = "100%")
                          ),
  
  columns = list(
      logo_home = colDef(name = "",
                         maxWidth = 54,
                         align = "center",
      cell = function(value) {
        if (!is.na(value)){
        img_src <- knitr::image_uri(sprintf("logo/%s", value))
        image <- img(src = img_src, style = "height: 48px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 48px", image)
          )}
      }
      ),
     
    elo_home = colDef(
      name = "",
      maxWidth = 68,
      align = "right",
      style = list(
        fontWeight = 500,
        paddingLeft = "0px"
    )
      
    ),
    dif_home = colDef(
      name = "",
      maxWidth = 44,
      align = "left",
      cell = function(value) {
          if (!is.na(value)){
        if (value >= 0) paste0("+", value, "") else paste0("", value, "")
      }},
      style = function(value) {
        if (!is.na(value)){
        color <- if (value > 0) {
          "#008000"
        } else if (value < 0) {
          "#e00000"
        }
        list(fontWeight = 400, color = color, paddingRight = "-0px", fontSize = "1.175rem")
        
      }},
      
    ),
    team_home = colDef(
      name = "",
      maxWidth  = 125,
      align = "right",
      style = list(paddingRight = "20px")
    ),
    points_home = colDef(
      name = "",
      maxWidth = 18,
      align = "center",
      style = list(fontWeight = 500, fontSize = "2.375rem")
    ),
     tire = colDef(
      name = "",
      maxWidth = 12,
      align = "center",
      style = list(fontWeight = 500, fontSize = "2.375rem")
    ),
     points_away = colDef(
      name = "",
      maxWidth = 18,
      align = "center",
      style = list(fontWeight = 500, fontSize = "2.375rem")
    ),
     team_away = colDef(
      name = "",
      maxWidth = 125,
      align = "left",
      style = list(paddingLeft = "20px")
    ),
    elo_away = colDef(
      name = "",
      maxWidth = 68,
      align = "right",
      style = list(fontWeight = 500, paddingLeft = "0px")
      
    ),
     dif_away = colDef(
      name = "",
      maxWidth = 44,
      align = "left",
      cell = function(value) {
        if (!is.na(value)){
        if (value >= 0) paste0("+", value) else value
      }},
      style = function(value) {
        if (!is.na(value)){
        color <- if (value > 0) {
          "#008000"
        } else if (value < 0) {
          "#e00000"
        }
        list(fontWeight = 400, color = color, paddingRight = "-0px", fontSize = "1.175rem")
      }},
      
    ),
      logo_away = colDef(name = "",
                         maxWidth = 54,
                         align = "center",
      cell = function(value) {
        if (!is.na(value)){
        img_src <- knitr::image_uri(sprintf("logo/%s", value))
        image <- img(src = img_src, style = "height: 48px;", alt = value)
        tagList(
          div(style = "display: inline-block; width: 48px", image)
          )
      }}
      )
  ),
    defaultPageSize = 14,
    borderless = TRUE,
    height = 650,
    defaultColDef = colDef(headerStyle = list(fontWeight=200), vAlign = "center",
                           style = list(minHeight = "38px")),
    
)


```

## Including Plots

You can also embed plots, for example:

```{css styles, eval=FALSE, echo = FALSE}
.spi-rating {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: auto;
  width: 3.875rem;
  height: 3.875rem;
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  color: #000;
  font-size: 0.0125rem;
  letter-spacing: -1px;
}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
